added categories parser
apfirsov/marketplaces_parser pull request #2
Opened 2023-02-02 18:38 UTC by crush-on-anechka

loader/categories.py теперь стягивает с WB список категорий, валидирует категории с помощью модели pydantic, описанной в loader/schemas.py, затем поле childs конвертируется в булевое и в таком виде передается в БД

2023-02-02 21:07 UTC, apfirsov requested changes
Добавил замечаний

2023-02-02 21:07 UTC, apfirsov commented on parser_service/loader/categories.py
>  s = Session(bind=engine)
Создастся одна сессия на все время работы приложения, это плохо. Сессию можно открывать непосредственно перед записью в бд и потом закрыть.

2023-02-04 00:57 UTC, crush-on-anechka commented on parser_service/loader/constants.py
> +MAIN_MENU: str = ('https://static-basket-01.wb.ru/vol0/'
возможно есть смысл собрать папочку settings, в которую положим settings.py и constants.py

2023-02-04 13:21 UTC, apfirsov approved these changes
Добавил пару комментов, кторые можно в след итерации допилить

2023-02-04 13:21 UTC, apfirsov commented on parser_service/loader/categories.py
> +        try:
если так, то зачем вложенный try? он ничего не делает в этом случае. Если его убрать ничего не поменяется)

2023-02-04 13:21 UTC, apfirsov commented on parser_service/loader/constants.py
> +MAIN_MENU: str = ('https://static-basket-01.wb.ru/vol0/'
да, можно так, чтобы настройки в одном месте крутились

2023-02-04 13:23 UTC, merged