fixed schema and exceptions
apfirsov/marketplaces_parser pull request #5
Opened 2023-02-11 00:22 UTC by crush-on-anechka

поправил поле parent в schema (было parent_id), добавил валидацию (если у категории нет поля parent, то должно быть поле landing), переиграл эксепшны

2023-02-12 21:27 UTC, apfirsov requested changes
Кое-что нужно поправить)

2023-02-12 21:27 UTC, apfirsov commented on parser_service/loader/exceptions.py
> +        return self.message
Если обратиться напрямую к этому классу будет ошибка, ведь message нет. Ниже добавлю связанный коммент

2023-02-12 21:27 UTC, apfirsov commented on parser_service/loader/exceptions.py
> +        self.message = 'Server returned null value'
аргумент message не используется. Прикольнее будет создать атрибут класса и переопределять просто его, не лазая в инит Типа такого:

```
class BaseParserException(Exception):
    message = 'Unknown parser error'

    def __str__(self) -> str:
        return self.message

class EmptyResponseError(BaseParserException):
    message = 'Server returned null value'
 ```

2023-02-12 21:27 UTC, apfirsov commented on parser_service/loader/schemas.py
>      shard: Optional[str]
Вопрос на подумать обсудить: Мне не нравиться, что Optional позволяет полю отсутствовать в принципе. Мы можем как-то переиграть, чтобы поля, которые должны точно быть хоть и пустые, проверялись на наличие?

2023-02-12 21:27 UTC, apfirsov commented on parser_service/loader/categories.py
> +            raise error
попрежнему не понимаю, зачем 2 уровня вложенности try?

2023-02-12 21:27 UTC, apfirsov commented on parser_service/loader/schemas.py
> +        v['parent_id'] = v.pop('parent')
мы переименовали parent_id в parent в моделях)), по идее это теперь не надо уже))

2023-02-13 11:09 UTC, crush-on-anechka commented on parser_service/loader/schemas.py
>      shard: Optional[str]
Согласен, что это не очень хорошо, но не совсем понимаю что можно сделать. Мы же тут проверяем то, что приходит от WB, а у WB если в поле нет значения, то оно просто отсутствует.

2023-02-13 11:13 UTC, crush-on-anechka commented on parser_service/loader/categories.py
> +            raise error
первый внутренний трай отлавливает JSONDecodeError при отправке запроса, второй внутренний трай отлавливает ValidationError при обработке пайдантиком, а все это обернуто в трай-эксепт, который отлавливает все остальное

2023-02-13 11:15 UTC, crush-on-anechka commented on parser_service/loader/exceptions.py
> +        self.message = 'Server returned null value'
прикольно!

2023-02-14 21:09 UTC, apfirsov commented on parser_service/loader/schemas.py
>      shard: Optional[str]
ну пусть пока так будет, потом может что-то докрутим в этой части

2023-02-15 22:14 UTC, apfirsov approved these changes
Позже можно будет еще расширить эксепшины. Например, если response.status_code != HTTPStatus.OK: то фиксировать, а какой именно статус и тп.

2023-02-15 22:15 UTC, merged